services:
  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./uploaded_docs:/app/uploaded_docs
    ports:
      - "5001:5001"
    env_file:
      - backend/.env
    environment:
      - TZ=Europe/Rome
    
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    #stdin_open: true
    #tty: true
    depends_on:
      - backend