services:
  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./uploaded_docs:/app/uploaded_docs
    ports:
      - "5001:5001"
    env_file:
      - backend/.env
    environment:
      - TZ=Europe/Rome
    networks:
      - app-network
    
  #frontend:
  #  build:
  #    context: .
  #    dockerfile: frontend/Dockerfile
  #  ports:
   #   - "3000:3000"
    #stdin_open: true
    #tty: true
  #  depends_on:
   #   - backend
    #networks:
     # - app-network

  static:
    image: nginx:1.25-alpine-slim
    ports:
      - 8070:80
    depends_on:
      - backend
    volumes: 
      - ./frontend/build:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "wget -nv -t1 --spider http://localhost || exit 1"]


networks:
  app-network:
    driver: bridge